export const BORED_CONTENT = {
  ru: {
    eyebrow: 'Raf</>Console Playground',
    titlePrimary:
        'Лопай шарики',

    titleSecondary:
        'Снимай напряжение',
    subtitle:
      'Восемь режимов, полноэкранная арена, короткие и непрерывные электрические разряды, а также AIM-настройки под мышь и прицел.',
    scoring: 'Режим игры',
    scoreMode: 'На очки',
    relaxMode: 'Для удовольствия',
    play: 'Играть',
    start: 'Начать',
    stop: 'Стоп',
    close: 'Закрыть игру',
    running: 'Игра идёт',
    ready: 'Готово к запуску',
    finished: 'Сессия остановлена',
    countdown: 'Приготовьтесь',
    score: 'Очки',
    hits: 'Попадания',
    misses: 'Пропуски',
    time: 'Время',
    currentMode: 'Режим',
    fullscreenReadyTitle: 'Всё готово',
    fullscreenReadyText:
      'Нажмите «Начать». Обычный клик создаёт короткий удар, а удержание с движением запускает непрерывный разряд.',
    fullscreenFinishedTitle: 'Сессия завершена',
    fullscreenFinishedText:
      'Можно сразу начать ещё раз с теми же настройками или закрыть игру и изменить параметры.',
    fullscreenRunning:
      'ЛКМ — выстрел или разряд · ПКМ — прицел · Пробел — старт/стоп · Esc — освободить мышь',
    fullscreenRunningSniper:
      'ЛКМ — одиночный выстрел · ПКМ — оптика · удержание отключено · резкий рывок вниз компенсирует неточность',
    settingsTitle: 'Настройки игры',
    settingsSubtitle:
      'Все параметры сохраняются в браузере и применяются к следующему запуску.',
    currentModeSettings: 'Параметры режима',
    generalSettings: 'Сессия и сложность',
    effectSettings: 'Вспышки и молнии',
    audioSettings: 'Звуки разряда',
    aimSettings: 'Чувствительность и прицел',
    dragSettings: 'Удержание и ведение',
    comfortSettings: 'Управление и комфорт',
    crosshairSettings: 'Обычный прицел',
    crosshairBuilder: 'Конструктор прицела CS2',
    recoilSettings: 'Отдача',
    recoilTraining: 'Поведение оружия',
    sniperCrosshairSettings: 'Снайперский прицел',
    sniperCrosshairBuilder: 'Точная настройка оптики',
    presetVaultTitle: 'JSON-пресеты',
    presetVaultSubtitle: 'Локальное хранилище до 10 пресетов каждого вида',
    presetName: 'Название пресета',
    presetNamePlaceholder: 'Например, AWP reaction',
    savePreset: 'Сохранить',
    importJson: 'Импорт JSON',
    exportAllJson: 'Экспорт всех',
    loadPreset: 'Загрузить',
    exportPreset: 'JSON',
    deletePreset: 'Удалить пресет',
    noPresets: 'В этой категории пока нет сохранённых пресетов.',
    presetImportedName: 'Импортированный пресет',
    reactionLast: 'Последняя реакция',
    reactionBest: 'Лучшая реакция',
    presets: 'Пресеты',
    presetCalm: 'Спокойно',
    presetNormal: 'Нормально',
    presetFast: 'Быстро',
    presetExtreme: 'Экстрим',
    resetMode: 'Сбросить режим',
    resetAll: 'Сбросить всё',
    saved: 'Настройки сохраняются автоматически',
    modeLocked: 'Закройте игру, чтобы сменить режим.',
    unlimited: 'Без ограничения',
    secondsShort: 'с',
    millisecondsShort: 'мс',
    remShort: 'rem',
    percentShort: '%',
    pointsShort: 'очк.',
    enabled: 'Включено',
    disabled: 'Выключено',
    edpi: 'Расчётный eDPI',
    captureMouse: 'Захватить мышь',
    mouseCaptured: 'Мышь захвачена',
    scopeActive: 'Прицел включён',
    dragActive: 'Непрерывный разряд',
    presetTypes: {
      all: 'Все настройки',
      crosshair: 'Только обычный прицел',
      sniperCrosshair: 'Только снайперский прицел',
      bothCrosshairs: 'Оба прицела',
      settingsWithoutCrosshairs: 'Настройки без прицелов',
    },
    presetMessages: {
      nameRequired: 'Введите название пресета.',
      limitReached: 'Достигнут лимит: 10 пресетов этого вида.',
      saved: 'Пресет сохранён локально.',
      loaded: 'Пресет применён.',
      deleted: 'Пресет удалён.',
      imported: 'JSON успешно импортирован.',
      importError: 'Не удалось прочитать этот JSON-файл.',
    },
    crosshairStyles: {
      default: 'По умолчанию',
      defaultStatic: 'По умолчанию (статичный)',
      classic: 'Классический',
      classicDynamic: 'Классический динамический',
      classicStatic: 'Классический статичный',
      legacy: 'Наследуемый',
    },
    crosshairShapes: {
      cross: 'Перекрестие',
      t: 'Т-образный',
    },
    crosshairColors: {
      green: 'Зелёный CS2',
      yellow: 'Жёлтый',
      blue: 'Синий',
      cyan: 'Голубой',
      red: 'Красный',
      white: 'Белый',
      custom: 'Свой RGB',
    },
    sniperTrainingTypes: {
      tracking: 'Обычный снайперский',
      reaction: 'Тренировка реакции',
    },
    settings: {
      countdownSeconds: {
        label: 'Таймер перед стартом',
        description: 'Задержка между нажатием «Начать» и первым шариком.',
      },
      sessionDurationSeconds: {
        label: 'Длительность сессии',
        description: 'Автоматическая остановка игры через заданное время.',
      },
      maxActive: {
        label: 'Шаров одновременно',
        description: 'Общий предел объектов на игровом поле.',
      },
      adaptiveDifficulty: {
        label: 'Адаптивное ускорение',
        description: 'Постепенно сокращает паузы между появлениями.',
      },
      difficultyRamp: {
        label: 'Ускорение в минуту',
        description: 'Насколько быстрее становится игра каждую минуту.',
      },
      autoFullscreen: {
        label: 'Системный полноэкранный режим',
        description: 'Скрывает интерфейс браузера, если это разрешено устройством.',
      },
      pauseWhenHidden: {
        label: 'Пауза при сворачивании',
        description: 'Не считать пропуски, когда вкладка не видна.',
      },
      spawnMinMs: {
        label: 'Минимальная пауза',
        description: 'Самый короткий интервал между шариками.',
      },
      spawnMaxMs: {
        label: 'Максимальная пауза',
        description: 'Самый длинный интервал между шариками.',
      },
      lifetimeMs: {
        label: 'Время жизни шара',
        description: 'Сколько времени шар остаётся доступным для попадания.',
      },
      lifetimeMinMs: {
        label: 'Минимальное появление',
        description: 'Самое короткое время видимости в «Догонялках».',
      },
      lifetimeMaxMs: {
        label: 'Максимальное появление',
        description: 'Самое длинное время видимости в «Догонялках».',
      },
      nextDelayMs: {
        label: 'Пауза после шара',
        description: 'Задержка перед следующей целью в «Догонялках».',
      },
      sizeMinRem: {
        label: 'Минимальный размер',
        description: 'Размер самого маленького шара.',
      },
      sizeMaxRem: {
        label: 'Максимальный размер',
        description: 'Размер самого большого шара.',
      },
      chainRadiusPercent: {
        label: 'Радиус цепной реакции',
        description: 'Расстояние, на котором лопаются соседние шары.',
      },
      chainBonus: {
        label: 'Бонус за соседний шар',
        description: 'Дополнительные очки за каждый шар в цепочке.',
      },
      precisionBonus: {
        label: 'Бонус за центр',
        description: 'Дополнительные очки за попадание ближе к центру цели.',
      },
      missPenalty: {
        label: 'Штраф за пропуск',
        description: 'Сколько очков снимается за исчезнувший шар.',
      },
      flashEnabled: {
        label: 'Световая вспышка',
        description: 'Коротко подсвечивает экран в точке попадания.',
      },
      flashOpacity: {
        label: 'Яркость вспышки',
        description: 'Максимальная непрозрачность светового импульса.',
      },
      lightningEnabled: {
        label: 'Молнии',
        description: 'Проводит разряды от краёв экрана к месту попадания.',
      },
      lightningCount: {
        label: 'Количество молний',
        description: 'Сколько сторон экрана участвует в одном эффекте.',
      },
      lightningFadeMs: {
        label: 'Исчезновение следа',
        description: 'Скорость растворения молнии после отпускания.',
      },
      particlesEnabled: {
        label: 'Осколки света',
        description: 'Добавляет расходящиеся частицы в месте попадания.',
      },
      screenShakeEnabled: {
        label: 'Импульс экрана',
        description: 'Лёгкая встряска игрового поля при попадании.',
      },
      audioEnabled: {
        label: 'Звуки электричества',
        description: 'Включает короткие попадания и непрерывный разряд.',
      },
      shortSound: {
        label: 'Короткий звук',
        description: 'Проигрывается полностью при успешном одиночном попадании.',
      },
      shortVolume: {
        label: 'Громкость короткого удара',
        description: 'Громкость ShortShock или HadShoatShock.',
      },
      longSound: {
        label: 'Длинный звук',
        description: 'Бесшовно повторяется при удержании и ведении курсора.',
      },
      longVolume: {
        label: 'Громкость непрерывного разряда',
        description: 'Громкость выбранного LongShock.',
      },
      mouseDpi: {
        label: 'DPI мыши',
        description: 'Используется для отображения привычного eDPI.',
      },
      mouseSensitivity: {
        label: 'Чувствительность мыши',
        description: 'Основной множитель перемещения игрового прицела.',
      },
      zoomSensitivity: {
        label: 'Чувствительность в прицеле',
        description: 'Отдельный множитель доведения при включённом прицеле.',
      },
      scopeZoom: {
        label: 'Увеличение прицела',
        description: 'Насколько приближается игровое поле при прицеливании.',
      },
      rightClickScopeEnabled: {
        label: 'Прицел по правой кнопке',
        description: 'Переключает снайперский прицел в любом обычном режиме.',
      },
      pointerLockEnabled: {
        label: 'Захват мыши',
        description: 'Позволяет тренировать AIM без упора курсора в края экрана.',
      },
      rawInputEnabled: {
        label: 'Необработанное движение',
        description: 'Запрашивает raw input без системного ускорения, если браузер поддерживает.',
      },
      longPressEnabled: {
        label: 'Непрерывный разряд',
        description: 'Удержание ЛКМ и ведение курсора лопает цели по траектории.',
      },
      longPressDelayMs: {
        label: 'Задержка удержания',
        description: 'Через сколько миллисекунд клик превращается в разряд.',
      },
      dragStartDistancePx: {
        label: 'Порог движения',
        description: 'Минимальное движение мыши до запуска ведения.',
      },
      dragHitCooldownMs: {
        label: 'Частота разряда',
        description: 'Интервал проверки целей и обновления молний.',
      },
      dragLightningBranches: {
        label: 'Ветви молний',
        description: 'Сколько дополнительных ветвей появляется при ведении.',
      },
      showCustomCursor: {
        label: 'Игровой прицел',
        description: 'Показывает собственный курсор, зависящий от чувствительности.',
      },
      sniperTrainingType: {
        label: 'Вариант снайперской тренировки',
        description: 'Все цели видны сразу или обнаруживаются только внутри оптики.',
      },
      sniperTargetCount: {
        label: 'Целей одновременно',
        description: 'Количество активных целей в снайперской тренировке.',
      },
      reactionRevealRadiusPercent: {
        label: 'Зона обнаружения',
        description: 'Размер области внутри оптики, в которой становится видна цель.',
      },
      crosshairStyle: {
        label: 'Стиль прицела CS2',
        description: 'Статичное или динамическое поведение линий при движении и отдаче.',
      },
      followRecoil: {
        label: 'Следовать за отдачей',
        description: 'Смещает прицел вместе с отдачей. Доступно только при включённой отдаче.',
      },
      centerDot: {
        label: 'Точка в центре',
        description: 'Показывает центральную точку обычного прицела.',
      },
      crosshairLength: {
        label: 'Длина линий',
        description: 'Длина четырёх сегментов прицела.',
      },
      crosshairThickness: {
        label: 'Толщина линий',
        description: 'Толщина сегментов обычного прицела.',
      },
      crosshairGap: {
        label: 'Зазор',
        description: 'Расстояние между центром и линиями прицела.',
      },
      crosshairOutlineEnabled: {
        label: 'Обводка',
        description: 'Добавляет тёмный контур вокруг линий для контраста.',
      },
      crosshairOutlineThickness: {
        label: 'Толщина обводки',
        description: 'Размер внешнего контура прицела.',
      },
      crosshairColor: {
        label: 'Цвет прицела CS2',
        description: 'Готовый цвет или полностью пользовательский RGB.',
      },
      crosshairRed: {
        label: 'Красный',
        description: 'Красный канал пользовательского цвета.',
      },
      crosshairGreen: {
        label: 'Зелёный',
        description: 'Зелёный канал пользовательского цвета.',
      },
      crosshairBlue: {
        label: 'Синий',
        description: 'Синий канал пользовательского цвета.',
      },
      crosshairOpacity: {
        label: 'Прозрачность',
        description: 'Альфа-канал прицела в диапазоне CS2 от 0 до 255.',
      },
      crosshairShape: {
        label: 'Форма',
        description: 'Полное перекрестие или Т-образный вариант без верхней линии.',
      },
      recoilEnabled: {
        label: 'Включить отдачу',
        description: 'Каждый выстрел смещает точку попадания вверх и немного в сторону.',
      },
      recoilStrengthPx: {
        label: 'Сила отдачи',
        description: 'Вертикальный импульс одного выстрела.',
      },
      recoilHorizontalVariance: {
        label: 'Боковой разброс отдачи',
        description: 'Случайное горизонтальное отклонение импульса.',
      },
      recoilRecoveryMs: {
        label: 'Возврат после отдачи',
        description: 'Скорость плавного возвращения точки прицеливания.',
      },
      recoilResetDelayMs: {
        label: 'Пауза перед возвратом',
        description: 'Через сколько миллисекунд начинается восстановление.',
      },
      sniperExitDelayMs: {
        label: 'Задержка после выстрела',
        description: 'Через сколько начинается короткий цикл выхода из оптики.',
      },
      sniperShowInaccuracy: {
        label: 'Показывать неточность',
        description: 'При резком движении оптика размывается, а выстрел уходит немного вверх. Резкий рывок вниз компенсирует неточность.',
      },
      sniperReturnToScope: {
        label: 'Возвращаться в прицел',
        description: 'Автоматически восстанавливает оптический прицел после выстрела.',
      },
      sniperThickness: {
        label: 'Толщина снайперского прицела',
        description: 'Толщина линий внутри оптического круга.',
      },
      sniperCenterDotEnabled: {
        label: 'Центральная точка оптики',
        description: 'Показывает точку пересечения линий.',
      },
      sniperCenterDotSize: {
        label: 'Размер точки прицела',
        description: 'Диаметр центральной точки снайперского прицела.',
      },
      sniperLineLength: {
        label: 'Длина линий оптики',
        description: 'Насколько далеко линии расходятся от центра.',
      },
      sniperGap: {
        label: 'Зазор оптики',
        description: 'Свободное пространство вокруг центральной точки.',
      },
      presetType: {
        label: 'Тип пресета',
        description: 'Какая часть текущей конфигурации будет сохранена.',
      },
      vibrationEnabled: {
        label: 'Вибрация на телефоне',
        description: 'Короткий тактильный отклик, если устройство поддерживает.',
      },
      mobileHitBoost: {
        label: 'Расширение зоны нажатия',
        description: 'Увеличивает невидимую область попадания вокруг шара.',
      },
      arenaGridEnabled: {
        label: 'Сетка игрового поля',
        description: 'Показывает тонкую пространственную сетку на фоне.',
      },
      scoreFeedbackEnabled: {
        label: 'Показывать очки',
        description: 'Выводит +N или штраф рядом с целью.',
      },
    },
    modes: {
      grow: {
        number: '01',
        title: 'Волны',
        short: 'Рост из точки',
        description:
          'Шар появляется точкой и вырастает до размера третьей волны. Самое раннее попадание приносит 10 очков.',
      },
      static: {
        number: '02',
        title: 'Скорость',
        short: 'Статические шары',
        description:
          'Шары фиксированного размера появляются в разных местах. Лопайте их как можно быстрее.',
      },
      ninja: {
        number: '03',
        title: 'Фрут-ниндзя',
        short: 'Подброс снизу',
        description:
          'Шары разных размеров резко вылетают снизу, проходят дугу и падают обратно.',
      },
      rush: {
        number: '04',
        title: 'Бейсбол',
        short: 'Полёт на игрока',
        description:
          'Шары летят из глубины прямо на экран. Успейте попасть, пока они не пронеслись мимо.',
      },
      chase: {
        number: '05',
        title: 'Догонялки',
        short: 'Поймай момент',
        description:
          'Один быстрый шар появляется в случайном месте на короткое время и сразу исчезает.',
      },
      rain: {
        number: '06',
        title: 'Ливень',
        short: 'Падение сверху',
        description:
          'Поток шаров падает сверху под разными углами и с разной скоростью.',
      },
      chain: {
        number: '07',
        title: 'Цепная реакция',
        short: 'Один удар — серия',
        description:
          'Попадание взрывает ближайшие цели и начисляет бонус за цепочку.',
      },
      sniper: {
        number: '08',
        title: 'Снайпер',
        short: 'Доведение и реакция',
        description:
          'Обычная тренировка показывает все цели, а тренировка реакции открывает их только внутри оптики и измеряет время попадания.',
      },
    },
  },
  en: {
    eyebrow: 'Raf</>Console Playground',
    titlePrimary:
        'Pop bubbles',

    titleSecondary:
        'Clear your head',
    subtitle:
      'Eight modes, a fullscreen arena, short and continuous electrical discharges, plus mouse and scope AIM controls.',
    scoring: 'Play style',
    scoreMode: 'Score mode',
    relaxMode: 'Just for fun',
    play: 'Play',
    start: 'Start',
    stop: 'Stop',
    close: 'Close game',
    running: 'Game running',
    ready: 'Ready to start',
    finished: 'Session stopped',
    countdown: 'Get ready',
    score: 'Score',
    hits: 'Hits',
    misses: 'Misses',
    time: 'Time',
    currentMode: 'Mode',
    fullscreenReadyTitle: 'Everything is ready',
    fullscreenReadyText:
      'Press Start. A normal click plays a short impact; holding and moving starts the continuous discharge.',
    fullscreenFinishedTitle: 'Session complete',
    fullscreenFinishedText:
      'Start again with the same configuration or close the arena and adjust the settings.',
    fullscreenRunning:
      'LMB — shot/discharge · RMB — scope · Space — start/stop · Esc — release mouse',
    fullscreenRunningSniper:
      'LMB — single shot · RMB — scope · holding is disabled · a sharp downward flick compensates inaccuracy',
    settingsTitle: 'Game settings',
    settingsSubtitle:
      'Every option is saved in your browser and applied to the next run.',
    currentModeSettings: 'Mode parameters',
    generalSettings: 'Session and difficulty',
    effectSettings: 'Flash and lightning',
    audioSettings: 'Discharge audio',
    aimSettings: 'Sensitivity and scope',
    dragSettings: 'Hold and tracking',
    comfortSettings: 'Controls and comfort',
    crosshairSettings: 'Standard crosshair',
    crosshairBuilder: 'CS2 crosshair builder',
    recoilSettings: 'Recoil',
    recoilTraining: 'Weapon behaviour',
    sniperCrosshairSettings: 'Sniper crosshair',
    sniperCrosshairBuilder: 'Fine scope configuration',
    presetVaultTitle: 'JSON presets',
    presetVaultSubtitle: 'Local storage for up to 10 presets of each type',
    presetName: 'Preset name',
    presetNamePlaceholder: 'For example, AWP reaction',
    savePreset: 'Save',
    importJson: 'Import JSON',
    exportAllJson: 'Export all',
    loadPreset: 'Load',
    exportPreset: 'JSON',
    deletePreset: 'Delete preset',
    noPresets: 'There are no saved presets in this category yet.',
    presetImportedName: 'Imported preset',
    reactionLast: 'Last reaction',
    reactionBest: 'Best reaction',
    presets: 'Presets',
    presetCalm: 'Calm',
    presetNormal: 'Normal',
    presetFast: 'Fast',
    presetExtreme: 'Extreme',
    resetMode: 'Reset mode',
    resetAll: 'Reset all',
    saved: 'Settings are saved automatically',
    modeLocked: 'Close the game before changing modes.',
    unlimited: 'Unlimited',
    secondsShort: 's',
    millisecondsShort: 'ms',
    remShort: 'rem',
    percentShort: '%',
    pointsShort: 'pts',
    enabled: 'Enabled',
    disabled: 'Disabled',
    edpi: 'Calculated eDPI',
    captureMouse: 'Capture mouse',
    mouseCaptured: 'Mouse captured',
    scopeActive: 'Scope enabled',
    dragActive: 'Continuous discharge',
    presetTypes: {
      all: 'All settings',
      crosshair: 'Standard crosshair only',
      sniperCrosshair: 'Sniper crosshair only',
      bothCrosshairs: 'Both crosshairs',
      settingsWithoutCrosshairs: 'Settings without crosshairs',
    },
    presetMessages: {
      nameRequired: 'Enter a preset name.',
      limitReached: 'The limit of 10 presets for this type has been reached.',
      saved: 'Preset saved locally.',
      loaded: 'Preset applied.',
      deleted: 'Preset deleted.',
      imported: 'JSON imported successfully.',
      importError: 'This JSON file could not be read.',
    },
    crosshairStyles: {
      default: 'Default',
      defaultStatic: 'Default static',
      classic: 'Classic',
      classicDynamic: 'Classic dynamic',
      classicStatic: 'Classic static',
      legacy: 'Legacy',
    },
    crosshairShapes: {
      cross: 'Cross',
      t: 'T-shaped',
    },
    crosshairColors: {
      green: 'CS2 green',
      yellow: 'Yellow',
      blue: 'Blue',
      cyan: 'Cyan',
      red: 'Red',
      white: 'White',
      custom: 'Custom RGB',
    },
    sniperTrainingTypes: {
      tracking: 'Standard sniper',
      reaction: 'Reaction training',
    },
    settings: {
      countdownSeconds: { label: 'Start countdown', description: 'Delay between Start and the first bubble.' },
      sessionDurationSeconds: { label: 'Session duration', description: 'Automatically stop after a selected time.' },
      maxActive: { label: 'Bubbles at once', description: 'Global object limit inside the arena.' },
      adaptiveDifficulty: { label: 'Adaptive acceleration', description: 'Gradually shortens delays between spawns.' },
      difficultyRamp: { label: 'Acceleration per minute', description: 'How much faster the game gets each minute.' },
      autoFullscreen: { label: 'System fullscreen', description: 'Hides browser UI when the device allows it.' },
      pauseWhenHidden: { label: 'Pause when hidden', description: 'Do not count misses while the tab is hidden.' },
      spawnMinMs: { label: 'Minimum delay', description: 'Shortest interval between bubbles.' },
      spawnMaxMs: { label: 'Maximum delay', description: 'Longest interval between bubbles.' },
      lifetimeMs: { label: 'Bubble lifetime', description: 'How long each bubble remains hittable.' },
      lifetimeMinMs: { label: 'Minimum visibility', description: 'Shortest Chase target lifetime.' },
      lifetimeMaxMs: { label: 'Maximum visibility', description: 'Longest Chase target lifetime.' },
      nextDelayMs: { label: 'Delay after target', description: 'Pause before the next Chase target.' },
      sizeMinRem: { label: 'Minimum size', description: 'Size of the smallest bubble.' },
      sizeMaxRem: { label: 'Maximum size', description: 'Size of the largest bubble.' },
      chainRadiusPercent: { label: 'Chain radius', description: 'Distance that detonates neighbouring bubbles.' },
      chainBonus: { label: 'Neighbour bonus', description: 'Extra points for every chained bubble.' },
      precisionBonus: { label: 'Center bonus', description: 'Extra score for landing closer to the target center.' },
      missPenalty: { label: 'Miss penalty', description: 'Points removed for an expired bubble.' },
      flashEnabled: { label: 'Light flash', description: 'Briefly lights the arena at the impact point.' },
      flashOpacity: { label: 'Flash brightness', description: 'Maximum opacity of the light pulse.' },
      lightningEnabled: { label: 'Lightning', description: 'Draws bolts from arena edges to the impact.' },
      lightningCount: { label: 'Lightning count', description: 'Number of screen sides used per impact.' },
      lightningFadeMs: { label: 'Trail fade', description: 'How quickly bolts dissolve.' },
      particlesEnabled: { label: 'Light shards', description: 'Adds outward particles around the impact.' },
      screenShakeEnabled: { label: 'Arena impulse', description: 'A subtle arena shake on a hit.' },
      audioEnabled: { label: 'Electrical audio', description: 'Enables short hits and continuous discharge.' },
      shortSound: { label: 'Short sound', description: 'Plays completely after a successful single hit.' },
      shortVolume: { label: 'Short impact volume', description: 'Volume for ShortShock or HadShoatShock.' },
      longSound: { label: 'Long sound', description: 'Loops seamlessly while holding and tracking.' },
      longVolume: { label: 'Continuous volume', description: 'Volume for the selected LongShock.' },
      mouseDpi: { label: 'Mouse DPI', description: 'Used to show a familiar eDPI value.' },
      mouseSensitivity: { label: 'Mouse sensitivity', description: 'Main movement multiplier for the game crosshair.' },
      zoomSensitivity: { label: 'Scoped sensitivity', description: 'Separate fine-aim multiplier while scoped.' },
      scopeZoom: { label: 'Scope zoom', description: 'How strongly the arena is magnified while aiming.' },
      rightClickScopeEnabled: { label: 'Right-click scope', description: 'Toggles the sniper scope in every regular mode.' },
      pointerLockEnabled: { label: 'Mouse capture', description: 'Allows AIM training without hitting screen edges.' },
      rawInputEnabled: { label: 'Raw movement', description: 'Requests unadjusted input where supported.' },
      longPressEnabled: { label: 'Continuous discharge', description: 'Hold LMB and track across targets.' },
      longPressDelayMs: { label: 'Hold delay', description: 'Time before a click becomes a continuous discharge.' },
      dragStartDistancePx: { label: 'Movement threshold', description: 'Minimum movement before tracking begins.' },
      dragHitCooldownMs: { label: 'Discharge rate', description: 'Target check and lightning update interval.' },
      dragLightningBranches: { label: 'Lightning branches', description: 'Additional branches shown while tracking.' },
      showCustomCursor: { label: 'Game crosshair', description: 'Shows a sensitivity-controlled custom cursor.' },
      sniperTrainingType: { label: 'Sniper training variant', description: 'Show all targets or reveal them only inside the scope.' },
      sniperTargetCount: { label: 'Simultaneous targets', description: 'Number of active targets in sniper training.' },
      reactionRevealRadiusPercent: { label: 'Detection area', description: 'Size of the area inside the scope that reveals a target.' },
      crosshairStyle: { label: 'CS2 crosshair style', description: 'Static or dynamic line behaviour during movement and recoil.' },
      followRecoil: { label: 'Follow recoil', description: 'Moves the crosshair with recoil. Available only when recoil is enabled.' },
      centerDot: { label: 'Center dot', description: 'Shows a dot in the center of the standard crosshair.' },
      crosshairLength: { label: 'Line length', description: 'Length of the four crosshair segments.' },
      crosshairThickness: { label: 'Line thickness', description: 'Thickness of the standard crosshair segments.' },
      crosshairGap: { label: 'Gap', description: 'Distance between the center and crosshair lines.' },
      crosshairOutlineEnabled: { label: 'Outline', description: 'Adds a dark contour around the lines for contrast.' },
      crosshairOutlineThickness: { label: 'Outline thickness', description: 'Size of the outer crosshair contour.' },
      crosshairColor: { label: 'CS2 crosshair color', description: 'Choose a built-in color or a fully custom RGB value.' },
      crosshairRed: { label: 'Red', description: 'Red channel of the custom color.' },
      crosshairGreen: { label: 'Green', description: 'Green channel of the custom color.' },
      crosshairBlue: { label: 'Blue', description: 'Blue channel of the custom color.' },
      crosshairOpacity: { label: 'Opacity', description: 'Crosshair alpha value from 0 to 255, matching CS2-style controls.' },
      crosshairShape: { label: 'Shape', description: 'A full cross or a T-shaped variant without the top line.' },
      recoilEnabled: { label: 'Enable recoil', description: 'Each shot shifts the impact point upward and slightly sideways.' },
      recoilStrengthPx: { label: 'Recoil strength', description: 'Vertical impulse produced by one shot.' },
      recoilHorizontalVariance: { label: 'Horizontal recoil variance', description: 'Random sideways deviation of each impulse.' },
      recoilRecoveryMs: { label: 'Recoil recovery', description: 'How quickly the aim point smoothly returns.' },
      recoilResetDelayMs: { label: 'Recovery delay', description: 'Delay before recoil recovery begins.' },
      sniperExitDelayMs: { label: 'Post-shot scope delay', description: 'Delay before the short scope cycling animation begins.' },
      sniperShowInaccuracy: { label: 'Show scope inaccuracy', description: 'Fast movement blurs the scope and moves the shot slightly upward. A sharp downward flick compensates it.' },
      sniperReturnToScope: { label: 'Return to scope', description: 'Automatically restores the scope after a shot.' },
      sniperThickness: { label: 'Sniper crosshair thickness', description: 'Thickness of the lines inside the scope.' },
      sniperCenterDotEnabled: { label: 'Scope center dot', description: 'Shows a dot at the line intersection.' },
      sniperCenterDotSize: { label: 'Scope dot size', description: 'Diameter of the sniper crosshair center dot.' },
      sniperLineLength: { label: 'Scope line length', description: 'How far the lines extend from the center.' },
      sniperGap: { label: 'Scope gap', description: 'Free space around the center dot.' },
      presetType: { label: 'Preset type', description: 'Select which part of the current configuration is saved.' },
      vibrationEnabled: { label: 'Phone vibration', description: 'Short haptic feedback on supported devices.' },
      mobileHitBoost: { label: 'Touch target expansion', description: 'Adds an invisible hittable area around bubbles.' },
      arenaGridEnabled: { label: 'Arena grid', description: 'Shows a subtle spatial grid in the background.' },
      scoreFeedbackEnabled: { label: 'Score feedback', description: 'Shows +N or a penalty near the target.' },
    },
    modes: {
      grow: { number: '01', title: 'Waves', short: 'Grow from a point', description: 'A bubble starts as a point and grows to the third-wave size. The earliest hit is worth 10 points.' },
      static: { number: '02', title: 'Speed', short: 'Static bubbles', description: 'Fixed-size bubbles appear around the arena. Pop each one as quickly as possible.' },
      ninja: { number: '03', title: 'Fruit ninja', short: 'Launch from below', description: 'Different-sized bubbles shoot up, follow an arc and fall back down.' },
      rush: { number: '04', title: 'Baseball', short: 'Rush toward you', description: 'Bubbles fly out of the distance toward the screen.' },
      chase: { number: '05', title: 'Chase', short: 'Catch the moment', description: 'One fast bubble appears briefly at a random position.' },
      rain: { number: '06', title: 'Downpour', short: 'Fall from above', description: 'A stream of bubbles falls from above at different angles and speeds.' },
      chain: { number: '07', title: 'Chain reaction', short: 'One hit, many pops', description: 'A hit detonates nearby targets and builds a chain bonus.' },
      sniper: { number: '08', title: 'Sniper', short: 'Tracking and reaction', description: 'Standard training shows every target, while reaction training reveals targets only inside the scope and measures reaction time.' },
    },
  },
};
